<h1 id="bio">Biographie</h1>
<main id="biographie" class="container"> 

      <section id="prouve">

            <div id="content">

                  <ul class="timeline">
                        <li class="event" data-date="1901">
                        <p>Naissance à Paris, le 8 avril.</p>
                        </li>
                        <li class="event" data-date="1916-1921">
                        <p>Il apprend la ferronnerie dans l’atelier d’Emile Robert à Enghien, puis de Szabo à Paris.</p>    
                        </li>
                        <li class="event" data-date="1924">
                        <p>Installation du premier atelier rue Custine à Nancy dans lequel il réalise des ferronneries ainsi que des luminaires, des grilles, des portes…</p>    
                        </li>
                        <li class="event" data-date="1926">
                        <p>Il rencontre et collabore avec Mallet–Stevens, Le Corbusier, Jeanneret et Herbé à Paris.</p>    
                        </li>
                        <li class="event" data-date="1929">
                        <p>Premier brevet pour cloison amovible.</p>    
                        </li>
                        <li class="event" data-date="1930">
                        <p>Membre fondateur de <span class="italic">l’Union des Artistes Modernes</span> (UAM).</p>    
                        </li>
                        <li class="event" data-date="1931">
                        <p>Ouverture d’un grand atelier rue des Jardiniers à Nancy, premiers meubles en séries. Il fonde la société anonyme <span class="italic">Les Ateliers Jean Prouvé</span>.</p>    
                        </li>
                        <li class="event" data-date="1938">
                        <p>Maison du peuple à Clichy (Beaudouin et Lods architectes).</p>    
                        </li>
                        <li class="event" data-date="1939-1944">
                        <p>Pendant la guerre, il entre dans la Résistance. A la fin de la guerre, il sera durant quelques mois maire de Nancy et délégué à l’Assemblée consultative.
                        Etudes d’habitations démontables. Construction de 400 maisons pour les sinistrés de Lorraine.</p>    
                        </li>
                        <li class="event" data-date="1947">
                        <p>Transfert de la société des <span class="italic">Ateliers Jean Prouvé à Maxéville</span>.</p>    
                        </li>
                        <li class="event" data-date="1947-1953">
                        <p>L’activité de l’usine de Maxéville attire beaucoup d’architectes.<span class="italic">L’Aluminium français</span> devient majoritaire des actions de l’usine, imposant de nouvelles méthodes. Prouvé quitte ses ateliers à Maxéville.</p>   
                        </li>
                        <li class="event" data-date="1954">
                        <p>Il construit sa maison à Nancy.</p>    
                        </li>
                        <li class="event" data-date="1956">
                        <p>Création à Paris de la société <span class="italic">Les Constructions Jean Prouvé.</span></p>    
                        </li>
                        <li class="event" data-date="1958">
                        <p>Il entre au Conservatoire National des Arts et Métiers où il enseignera jusqu’en 1969.
                        Les Constructions Jean Prouvé à Paris sont absorbées par la <span class="italic">Compagnie Industrielle de Matériel de Transport</span> (CIMT) où il partage ses activités entre responsable du département bâtiment et ingénieur conseil.</p>    
                        </li>
                        <li class="event" data-date="1956-1975">
                        <p>Très nombreuses réalisations dont la maison de l’Abbé Pierre, la maison saharienne, des bâtiments scolaires et universitaires, des stations essence, des centaines de milliers de m² de panneaux de façade-rideau.</p>    
                        </li>
                        <li class="event" data-date="1966">
                        <p>Il quitte la CIMT.</p>    
                        </li>
                        <li class="event" data-date="1971">
                        <p>Président du jury du concours pour le centre Georges Pompidou.</p>    
                        </li>
                        <li class="event" data-date="1981">
                        <p>Prix Erasme (créé en 1958 par le prince Bernhard des Pays-Bas, ce prix récompense des
                        personnes ou des institutions qui ont contribué à la diffusion de la culture européenne).</p>    
                        </li>
                        <li class="event" data-date="1984">
                        <p>23 mars, mort de Jean Prouvé à Nancy.</p>    
                        </li>
                  </ul>

            </div>

      </section>
      
</main>			

