<main id="constructions">

	<h1 id="construct">Constructions</h1>

	<div id="buildings" class="flexcontainer">
		<div id="maison-peuple" class="animated zoomIn" title ="Jean Prouvé - Maison du Peuple" >
			<span class="top"></span> 
			<span class="left"></span> 
			<span class="right"></span> 
			<span class="bottom"></span> 
			<span class="voileblanc"></span>
			<h2 class="building-name">Maison du Peuple</h2>
			<p>Clichy (1935-1939 – Beaudouin et Lods, architectes), façade</p>
		</div>

		<div id="maison-tropicale" class="animated zoomIn" title ="Jean Prouvé - Maisons Tropicales">
			<span class="top"></span> 
			<span class="left"></span> 
			<span class="right"></span> 
			<span class="bottom"></span> 
			<span class="voileblanc"></span>
			<h2 class="building-name">Maisons Tropicales</h2>
			<p>Niamey (Niger, 1949), Brazzaville (République du Congo, 1951)</p>
		</div>

		<div id="pavillon-alu" class="animated zoomIn" title ="Jean Prouvé - Pavillon du centenaire de l'aluminium">
			<span class="top"></span> 
			<span class="left"></span> 
			<span class="right"></span> 
			<span class="bottom"></span> 
			<span class="voileblanc"></span>
			<h2 class="building-name">Pavillon du centenaire de l'aluminium</h2>
			<p>Paris (1954)</p>
		</div>

		<div id="maison-malzeville" class="animated zoomIn" title ="Jean Prouvé - Maison personnelle">
			<span class="top"></span> 
			<span class="left"></span> 
			<span class="right"></span> 
			<span class="bottom"></span> 
			<span class="voileblanc"></span>
			<h2 class="building-name">Maison personnelle</h2>
			<p>Nancy (1954)</p>
		</div>

		<div id="cnit" class="animated zoomIn" title ="Jean Prouvé - CNIT">
			<span class="top"></span> 
			<span class="left"></span> 
			<span class="right"></span> 
			<span class="bottom"></span> 
			<span class="voileblanc"></span>
			<h2 class="building-name">CNIT</h2>
			<p>Paris la Défense (1956 – Zehrfuss, architecte), façade</p>
		</div>

		<div id="ecole-villejuif" class="animated zoomIn" title ="Jean Prouvé - Ecole provisoire de Villejuif">
			<span class="top"></span> 
			<span class="left"></span> 
			<span class="right"></span> 
			<span class="bottom"></span> 
			<span class="voileblanc"></span>
			<h2 class="building-name">Ecole provisoire de Villejuif</h2>
			<p>(1957)</p>
		</div>

		<div id="tour-nobel" class="animated zoomIn" title ="Jean Prouvé - Tour Nobel">
			<span class="top"></span> 
			<span class="left"></span> 
			<span class="right"></span> 
			<span class="bottom"></span> 
			<span class="voileblanc"></span>
			<h2 class="building-name">Tour Nobel</em></h2>
			<p>Paris la Défense (1967 – de Mailly et Depussé, architectes), façade</p>
		</div>

		<div id="siege-pcf" class="animated zoomIn" title ="Jean Prouvé - Siège du Parti Communiste">
			<span class="top"></span> 
			<span class="left"></span> 
			<span class="right"></span> 
			<span class="bottom"></span> 
			<span class="voileblanc"></span>
			<h2 class="building-name">Siège du Parti Communiste</h2>
			<p>Siège du PCF, Paris, (1970 - Oscar Niemeyer, architecte), façade</p>
		</div>

	</div>
				
</main>