<main id="index" class="container">  
   
   <section id="slider">

        <img id="sliderImage" src="" alt="">
        
        <div id="points-row">
            <div id="c1" class="point gold"></div>
            <div id="c2" class="point"></div>
            <div id="c3" class="point"></div>
        <div>

    </section>

    <h1 class="before">Jean Prouvé, créateur de génie</h1>

    <section id="avant-propos" class="flexcontainer">

        <article id="avant-propos-part1">

            <p> La genèse de ce site remonte à une promenade sur un marché dominical. Au hasard des étals où prenaient place antiquités, cartes postales, affiches ou beaux livres, mon regard s'est porté ce jour-là sur un ouvrage sobrement intitulé <span class="italic">Jean Prouvé</span>. Ce nom m'était familier tant l'homme a marqué de son empreinte le patrimoine artistique, culturel et industriel de Nancy, ma ville de naissance. Nombre de lieux y témoignent de son influence et de son attachement à la cité ducale. Une reconnaissance réciproque dont l'espace urbain se fait l'écho : rue, lycée, centre des congrès sont nommés en hommage à Jean Prouvé, alors qu'une galerie permanente lui est consacrée au sein du Musée des Beaux-Arts.</p> 
            
            <p>Je parcourais brièvement le livre et, avide d'en savoir plus sur l'homme et sur son oeuvre, décidais de me le procurer. Au fur et à mesure de mes lectures, je dédouvrais une personnalité aux multiples facettes et talents. Jean Prouvé fut avant tout un créateur de génie dont les travaux ont su trouver une résonnance internationale et ont inspiré des générations d'architectes, de designers ou d'ingénieurs. La construction et le mobilier notamment sont autant de domaines qu'il a profondément influencés grâce à une vision simple et exigente de son métier : faire cohabiter le bon et le beau. Patron humaniste, témoignant d'un grand égard envers les ouvriers des ses ateliers, il joua un rôle social important auprès des sinistrés de Lorraine dans le contexte de la Seconde Guerre mondiale. Engagé dans la résistance parallèlement à ses activités industrielles, il sera désigné maire provisoire de Nancy à la Libération, poste qu’il occupera pendant 8 mois.</p> 

            <p> Réalisé dans le cadre d'un projet de fin de formation en développement et intégration web, ce site se veut un modeste hommage au grand Homme que fût Jean Prouvé. Seule une partie de son oeuvre foisonnante est reproduite ici, notamment ses constructions les plus marquantes ainsi que quelques unes de ses pièces de mobilier les plus emblématiques. Les textes et illustrations sont issus de différentes sources, en particulier de publications du Musée des Beaux-Arts de Nancy ainsi que du très riche et esthétique <span class="italic">catalogue des expositions et du projet global Jean Prouvé 2012</span>.</p>

        </article>

        <article id="avant-propos-part2">

            <div id="citation">

                <div class="circle">
                    <i class="fas fa-quote-left"></i>
                </div>

                <div>
                    <p id="create">" Tous ces gens avaient l'amour du monde ouvrier, prônaient <span class="bold">une collaboration étroite entre des industriels, artistes et artisans</span>. Ils étaient révolutionnaires sur tous les plans et principalement sur le plan de de la production industrielle destinée au plus grand nombre. Leur idée était que <span class="bold">tout objet devait être un objet de qualité</span>, que toute architecture devait être de son époque. Leur règle principale que je me suis efforcé d'appliquer était la suivante&nbsp;:  <span class="bold">L'homme est sur terre pour créer.</span> "</p>
                </div>
                
            <div>
                <img src="img/signature.png" alt="Signature Jean Prouvé" id="signature"/> 
            </div>

        </article>

    </section>

    <section id="visite">
        <h2>Commencez la visite</h2>
        <a href="biographie.php"><i class="far fa-arrow-alt-circle-right"></i></a>
    </section>

</main>