<main id="liens" class="container">    
    
    <h1>Liens & Crédits photo</h1>

    <p>De par la richesse de leurs contenus textuels et visuels en lien avec l'oeuvre de Jean Prouvé, ces quelques liens m'ont été d'une grande aide dans la création de ce site :</p>

    <h2>Institutions, centres et musées</h2>
    <p><a href="http://mban.nancy.fr" target="_blank">Musée des Beaux-Arts de Nancy</a></p>
    <p><a href="https://www.nancy.fr/" target="_blank">Ville de Nancy</a></p>
    <p><a href="http://www.museehistoiredufer.fr" target="_blank">Musée de l'histoire du fer, Jarville</a></p>
    <p><a href="http://archives.meurthe-et-moselle.fr" target="_blank">Archives départementales de Meurthe-et-Moselle</a></p>
    <p><a href="https://www.citedelarchitecture.fr" target="_blank">Cité de l'architecture et du Patrimoine, Paris</a></p>
    <p><a href="https://www.centrepompidou.fr/" target="_blank">Centre Georges Pompidou, Paris</a></p>

    <h2>Galerie</h2>
    <p><a href="https://www.patrickseguin.com/fr/" target="_blank">Galerie Patrick Seguin, Paris</a></p>

    <h2>Autres</h2>
    <p><a href="https://www.taschen.com" target="_blank">Taschen</a></p>
    <p><a href="https://www.vitra.com" target="_blank">Vitra</a></p>

</main>