<main id="livre" class="container">    
    
    <h1>Livre</h1>

    <section id="description-livre">

        <p>Parmi les nombreux et passionants livres consacrés à Jean Prouvé, j'ai choisi de mettre en avant celui qui m'a inspiré la création de ce site. Il s'agit du <span class="italic">Catalogue des expositions et du projet global Jean Prouvé 2012</span>, ouvrage dont j'évoque la lecture sur la page d'accueil. Remarquablement documenté et bénéficiant d'un graphisme particulièrement soigné, ce livre est le catalogue commun à l'ensemble des manifestations organisées par la Ville de Nancy et la Communauté Urbaine du Grand Nancy en 2012.</p> 
        
        <h2 id="titre">Catalogue des expositions et du projet global Jean Prouvé 2012</h2>

		<article id="article-catalogue" class="flexcontainer">

			<div id="div-livre">

                <img id="livre-image" src="img/livre300.png" alt="Catalogue des expositions et du projet global Jean Prouvé 2012"/>  
                 
            </div>
            
			<div id="details-livre">

                <h3 id="Auteurs">Auteurs</h3>
                <p>Commissariat général : Claire Stoulig, directeur du musée des Beaux-Arts de Nancy - Commissariat scientifique : Catherine Coley, historienne de l'architecture</p>

                <h3 id="expositions ">Exposition</h3> 
                <p>Exposition "Jean Prouvé Nancy, Grand Nancy 2012" présentée du 30 juin au 28 octobre 2012 : "Jean Prouvé, ferronnier d'art" au musée de l'École de Nancy ; "Jean Prouvé à Nancy, construire des jours meilleurs" au Musée lorrain ; " La Maison tropicale" au musée des Beaux-Arts de Nancy ; "L'Émotion design, la collection d'Alexander van Vegesack" aux Galeries Poirel de Nancy<p>

                <h3 id="editeurs">Editeurs</h3>
                <p>Coéditions musée des Beaux-Arts, Nancy / Somogy éditions d'Art</p> 
                
            </div>
            
		</article>	
    
        <article id="savoir-plus">

            <h2>En savoir plus sur ce livre</h2>
            <a href="http://www.somogy.fr/livre/jean-prouve?ean=9782757205631" target="_blank"><i class="fas fa-book"></i></a>

        </article>

    <section>

</main>